fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    tomcat: "https://github.com/puppetlabs/puppetlabs-tomcat.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    git: "https://github.com/puppetlabs/puppetlabs-git.git"
  symlinks:
    opengrok: "#{source_dir}"
