---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.0
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
